config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: 1.0.0
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-aquamarine-ostrich.sh
        container: qc.acc_hilly-periwinkle-quetzal
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-peach-jackal.sh
        container: qc.doc_muzzy-xanthic-bird
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-amethyst-opossum.sh
        container: qc.doc_leaky-amethyst-llama
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-amethyst-hummingbird.sh
        container: qc.doc_jumpy-ultramarine-spaniel
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-tomato-shark.sh
        container: qc.lic_hilly-plum-woodpecker
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-lilac-cat.sh
        container: qc.sec_baggy-pumpkin-dormouse
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cinnamon-markhor.sh
        container: qc.sty_ugly-chocolate-ray
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-mauve-worm.sh
        container: qc.ver_shaggy-brass-discus
timeout: 5400
