config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cinnamon-okapi.sh
        container: qc.acc_wiggy-amaranth-spoonbill
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-denim-coati.sh
        container: qc.doc_skanky-thistle-newt
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-salmon-turkey.sh
        container: qc.doc_goopy-pear-civet
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-brown-oriole.sh
        container: qc.doc_cranky-celadon-mule
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cerise-uakari.sh
        container: qc.lic_lumpy-copper-vole
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-sepia-tzu.sh
        container: qc.met_nippy-corn-wallaby
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-denim-neanderthal.sh
        container: qc.sec_baggy-cream-bear
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-jade-otter.sh
        container: qc.sty_randy-grey-grouse
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-asparagus-tapir.sh
        container: qc.sty_boozy-chocolate-chicken
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-seashell-goat.sh
        container: qc.uni_squeaky-auburn-walrus
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-razzmatazz-greyhound.sh
        container: qc.ver_scaly-amaranth-coyote
timeout: 5400
