config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-russet-mongrel.sh
        container: qc.acc_chewy-azure-slug
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cobalt-kakapo.sh
        container: qc.doc_ugly-gamboge-cichlid
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-alizarin-rhinoceros.sh
        container: qc.doc_trippy-mustard-tapir
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-asparagus-toad.sh
        container: qc.doc_ready-eggplant-mouse
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-linen-millipede.sh
        container: qc.lic_wheezy-buff-seal
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-beige-russel.sh
        container: qc.met_trippy-flax-bonobo
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-copper-buzzard.sh
        container: qc.sec_queasy-taupe-mongrel
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-denim-capybara.sh
        container: qc.sty_gummy-gamboge-cockroach
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-persimmon-sponge.sh
        container: qc.sty_jumpy-alizarin-malamute
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-coral-rat.sh
        container: qc.uni_bluesy-ruby-mongrel
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-maroon-badger.sh
        container: qc.ver_hazy-pear-shrew
timeout: 5400
