config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-thistle-robin.sh
        container: qc.acc_bluesy-corn-zebu
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-malachite-insect.sh
        container: qc.doc_breezy-zucchini-fowl
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-amaranth-moorhen.sh
        container: qc.doc_silly-olive-woodpecker
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-teal-ragdoll.sh
        container: qc.doc_sloppy-corn-sheep
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-vermilion-bullfrog.sh
        container: qc.lic_frumpy-magnolia-monkey
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-sepia-falcon.sh
        container: qc.met_nippy-apricot-shrew
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-saffron-gibbon.sh
        container: qc.sec_sunny-tangerine-shrew
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-amber-kakapo.sh
        container: qc.sty_breezy-burgundy-javanese
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-magenta-wildebeest.sh
        container: qc.sty_nerdy-linen-turkey
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-puce-zebra.sh
        container: qc.uni_snippy-jade-tuatara
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-champagne-dunker.sh
        container: qc.ver_droopy-grey-zonkey
timeout: 5400
