config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-taupe-iguana.sh
        container: qc.acc_leaky-malachite-bongo
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-rose-weasel.sh
        container: qc.doc_boozy-wisteria-dodo
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-smalt-squid.sh
        container: qc.doc_wheezy-aqua-ocelot
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-tangerine-owl.sh
        container: qc.doc_sickly-ultramarine-turkey
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-denim-capuchin.sh
        container: qc.lic_scaly-tangerine-dormouse
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-crimson-stoat.sh
        container: qc.met_flimsy-cerulean-harrier
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-scarlet-beaver.sh
        container: qc.sec_blurry-alizarin-dunker
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-green-seahorse.sh
        container: qc.sty_sleepy-firebrick-sponge
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-ivory-kingfisher.sh
        container: qc.sty_chewy-aquamarine-gibbon
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-myrtle-hyena.sh
        container: qc.uni_seedy-xanthic-raccoon
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-amaranth-chicken.sh
        container: qc.ver_wheezy-gamboge-magpie
timeout: 5400
