config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: v1.3.5-rc.3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-peach-mole.sh
        container: qc.acc_geeky-brown-chow
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-mauve-gibbon.sh
        container: qc.doc_tasty-crimson-fly
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sangria-toucan.sh
        container: qc.doc_nippy-lavender-tarantula
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-wheat-coral.sh
        container: qc.doc_smelly-green-tang
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-pink-birman.sh
        container: qc.lic_beady-amber-armadillo
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-khaki-quoll.sh
        container: qc.met_lanky-olivine-maltese
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-aqua-hummingbird.sh
        container: qc.sec_snazzy-beige-tamarin
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-olivine-nightingale.sh
        container: qc.sty_frumpy-cerise-bison
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cerulean-grasshopper.sh
        container: qc.sty_hilly-denim-sloth
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-grey-buzzard.sh
        container: qc.ver_skimpy-vermilion-fowl
timeout: 5400
