config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: 1.3.4
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-flax-alligator.sh
        container: qc.acc_flaky-azure-deer
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-orchid-barnacle.sh
        container: qc.doc_dorky-blue-dachshund
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ultramarine-spitz.sh
        container: qc.doc_thirsty-olive-toucan
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-sepia-paradise.sh
        container: qc.doc_cozy-seashell-mau
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-russet-orangutan.sh
        container: qc.lic_hazy-corn-civet
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-khaki-snake.sh
        container: qc.met_stuffy-lilac-discus
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-aqua-fowl.sh
        container: qc.sec_droopy-cyan-caiman
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-champagne-wombat.sh
        container: qc.sty_crappy-celadon-bloodhound
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-lemon-lionfish.sh
        container: qc.sty_lumpy-mauve-octopus
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-emerald-stoat.sh
        container: qc.ver_droopy-rose-lizard
timeout: 5400
