config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-lime-schnauzer.sh
        container: qc.acc_fuzzy-turquoise-kiwi
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-sapphire-gorilla.sh
        container: qc.doc_smelly-mustard-tetra
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-khaki-crocodile.sh
        container: qc.doc_lanky-chocolate-squirrel
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-periwinkle-axolotl.sh
        container: qc.doc_slaphappy-cerulean-ray
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-pumpkin-wolf.sh
        container: qc.lic_sunny-cobalt-dugong
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-celadon-stingray.sh
        container: qc.met_sickly-mustard-zonkey
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-razzmatazz-hedgehog.sh
        container: qc.sec_skimpy-vermilion-hamster
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-puce-eel.sh
        container: qc.sty_messy-scarlet-horse
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-violet-audemer.sh
        container: qc.sty_snoopy-amaranth-gharial
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cream-avocet.sh
        container: qc.uni_wiggy-jade-tarsier
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-lime-zebu.sh
        container: qc.ver_leaky-ultramarine-bobcat
timeout: 5400
