config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-tangerine-hyrax.sh
        container: qc.acc_trippy-lavender-camel
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-amaranth-donkey.sh
        container: qc.doc_smelly-tangerine-uakari
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-celadon-coyote.sh
        container: qc.doc_gummy-ochre-okapi
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-amaranth-crab.sh
        container: qc.doc_droopy-cobalt-mammoth
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-wisteria-cockroach.sh
        container: qc.lic_hazy-silver-gecko
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-burgundy-binturong.sh
        container: qc.met_gamy-silver-koala
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-russet-binturong.sh
        container: qc.sec_scanty-denim-goat
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-jade-booby.sh
        container: qc.sty_leaky-viridian-rhinoceros
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-chartreuse-corgi.sh
        container: qc.sty_skinny-magnolia-saola
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-linen-warthog.sh
        container: qc.uni_cheeky-lavender-moth
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-olivine-walrus.sh
        container: qc.ver_pasty-cerulean-binturong
timeout: 5400
