config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cardinal-oriole.sh
        container: qc.acc_freaky-jade-centipede
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-chocolate-monster.sh
        container: qc.doc_beady-chartreuse-millipede
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-saffron-falcon.sh
        container: qc.doc_boozy-asparagus-zebu
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-corn-kingfisher.sh
        container: qc.lic_homely-crimson-butterfly
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-indigo-dodo.sh
        container: qc.ver_fuzzy-dandelion-ferret
timeout: 5400
