config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ivory-lynx.sh
        container: qc.acc_goopy-sangria-donkey
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-beige-ferret.sh
        container: qc.doc_trippy-olive-gorilla
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-indigo-tiger.sh
        container: qc.doc_sleazy-khaki-tapir
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-azure-bison.sh
        container: qc.doc_pretty-aqua-hippopotamus
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-copper-dollar.sh
        container: qc.lic_snoopy-mustard-dalmatian
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-smalt-eel.sh
        container: qc.met_queasy-vermilion-buzzard
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-magnolia-dragonfly.sh
        container: qc.sec_cranky-xanthic-birman
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-periwinkle-serval.sh
        container: qc.sty_shabby-salmon-swan
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-periwinkle-elephant.sh
        container: qc.sty_squeaky-chartreuse-molly
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-chocolate-wolf.sh
        container: qc.uni_beady-gold-chow
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-auburn-quokka.sh
        container: qc.ver_flabby-myrtle-heron
timeout: 5400
