config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-asparagus-liger.sh
        container: qc.acc_squeaky-ruby-snake
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-flax-collie.sh
        container: qc.doc_snappy-tan-pig
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-russet-squirrel.sh
        container: qc.doc_messy-orchid-hyena
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-periwinkle-cockroach.sh
        container: qc.doc_pasty-maroon-devil
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-white-shark.sh
        container: qc.lic_greasy-burgundy-ant
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-yellow-crab.sh
        container: qc.met_lousy-grey-bear
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-green-gar.sh
        container: qc.sec_skinny-beige-chicken
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-copper-lemur.sh
        container: qc.sty_silly-cinnamon-dragonfly
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-tomato-magpie.sh
        container: qc.sty_craggy-gold-chipmunk
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-turquoise-cattle.sh
        container: qc.uni_goopy-aqua-birman
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-red-dodo.sh
        container: qc.ver_messy-tan-albatross
timeout: 5400
