config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-magenta-donkey.sh
        container: qc.acc_hilly-carmine-wolfhound
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-grey-seahorse.sh
        container: qc.doc_beady-viridian-indri
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cinnabar-squid.sh
        container: qc.doc_snappy-eggplant-stoat
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-platinum-coyote.sh
        container: qc.doc_wiggy-amethyst-gopher
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-purple-mule.sh
        container: qc.lic_scaly-turquoise-termite
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-carmine-leopard.sh
        container: qc.met_fuzzy-smalt-toad
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-orchid-ladybird.sh
        container: qc.sec_lanky-platinum-cat
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-peach-greyhound.sh
        container: qc.sty_grumpy-buff-javanese
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-lemon-stoat.sh
        container: qc.sty_sunny-cinnamon-moose
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-turquoise-hyena.sh
        container: qc.ver_ready-ochre-bee
timeout: 5400
