config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cinnamon-dane.sh
        container: qc.acc_snazzy-smalt-reindeer
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-coral-leopard.sh
        container: qc.doc_wiggy-silver-vole
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-champagne-bordeaux.sh
        container: qc.doc_frumpy-auburn-javanese
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-lavender-flamingo.sh
        container: qc.doc_frumpy-red-toad
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-yellow-orangutan.sh
        container: qc.lic_sickly-aquamarine-toucan
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-maroon-panda.sh
        container: qc.met_flaky-bistre-clam
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-vermilion-whale.sh
        container: qc.sec_bluesy-silver-fousek
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-corn-mole.sh
        container: qc.sty_homey-cornflower-cheetah
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-viridian-salamander.sh
        container: qc.sty_whiny-khaki-toucan
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-turquoise-serval.sh
        container: qc.ver_dorky-lilac-jellyfish
timeout: 5400
