config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-coral-crab.sh
        container: qc.acc_smelly-periwinkle-chimpanzee
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-cyan-fly.sh
        container: qc.doc_greasy-chocolate-burmese
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-lavender-blue.sh
        container: qc.doc_nippy-fuchsia-mongrel
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-vermilion-spitz.sh
        container: qc.doc_fuzzy-ultramarine-russel
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-olivine-oyster.sh
        container: qc.lic_snazzy-aquamarine-cockroach
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-sapphire-woodlouse.sh
        container: qc.met_slaphappy-blue-booby
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-sapphire-squirt.sh
        container: qc.sec_fuzzy-fuchsia-crocodile
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-black-antelope.sh
        container: qc.sty_foggy-taupe-ladybird
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-ultramarine-cockroach.sh
        container: qc.sty_chewy-blue-akbash
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cardinal-orangutan.sh
        container: qc.uni_snippy-asparagus-hare
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-mustard-barracuda.sh
        container: qc.ver_skinny-purple-greyhound
timeout: 5400
