config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-gold-russel.sh
        container: qc.acc_ugly-wisteria-bombay
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-grey-mammoth.sh
        container: qc.doc_fuzzy-pumpkin-spitz
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cream-corgi.sh
        container: qc.doc_goopy-cardinal-spider
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-goldenrod-oyster.sh
        container: qc.doc_sloppy-bronze-iguana
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-silver-deer.sh
        container: qc.lic_craggy-emerald-moorhen
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-peach-camel.sh
        container: qc.met_pasty-firebrick-newt
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-ivory-goat.sh
        container: qc.sec_tacky-bistre-iguana
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-ultramarine-heron.sh
        container: qc.sty_geeky-lilac-argentino
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-lime-gharial.sh
        container: qc.sty_stuffy-lime-macaque
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-rose-manatee.sh
        container: qc.uni_blurry-apricot-sloth
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-seashell-markhor.sh
        container: qc.ver_lovely-bistre-capuchin
timeout: 5400
