config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-olivine-ferret.sh
        container: qc.acc_flimsy-linen-manatee
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-sapphire-fousek.sh
        container: qc.doc_randy-gold-manatee
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-magnolia-devil.sh
        container: qc.doc_queasy-peach-orangutan
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-teal-discus.sh
        container: qc.doc_zippy-chocolate-vulture
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-malachite-koala.sh
        container: qc.lic_snappy-gamboge-spider
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cream-dachsbracke.sh
        container: qc.met_frumpy-beige-vole
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-crimson-ray.sh
        container: qc.sec_sickly-linen-meerkat
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-turquoise-newfoundland.sh
        container: qc.sty_gimpy-amber-chinook
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-crimson-abyssinian.sh
        container: qc.sty_tacky-buff-rottweiler
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-razzmatazz-pinscher.sh
        container: qc.uni_lousy-brown-affenpinscher
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-chestnut-lionfish.sh
        container: qc.ver_wimpy-pumpkin-kudu
timeout: 5400
