config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-lemon-havanese.sh
        container: qc.acc_ugly-xanthic-zorse
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-amaranth-shrimp.sh
        container: qc.doc_greasy-cerulean-capuchin
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-amber-pinscher.sh
        container: qc.doc_jumpy-cardinal-kudu
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-eggplant-albatross.sh
        container: qc.doc_pasty-cobalt-foxhound
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cerulean-manatee.sh
        container: qc.lic_homey-green-wolf
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-ivory-collie.sh
        container: qc.met_pretty-ivory-angelfish
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cinnamon-uguisu.sh
        container: qc.sec_stealthy-amethyst-devil
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-heliotrope-sponge.sh
        container: qc.sty_snoopy-orchid-liger
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-goldenrod-duck.sh
        container: qc.sty_homey-sapphire-budgerigar
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-burgundy-booby.sh
        container: qc.uni_sickly-harlequin-kiwi
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-saffron-scorpion.sh
        container: qc.ver_muzzy-sangria-ray
timeout: 5400
