config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-lime-ferret.sh
        container: qc.acc_greasy-tangerine-balinese
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-orchid-bloodhound.sh
        container: qc.doc_gimpy-tomato-cockroach
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-white-armadillo.sh
        container: qc.doc_squeaky-wheat-whale
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-silver-deer.sh
        container: qc.doc_blurry-indigo-schnauzer
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-sangria-olm.sh
        container: qc.lic_squeaky-ecru-termite
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-charcoal-newfoundland.sh
        container: qc.met_squeaky-red-moorhen
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-goldenrod-kakapo.sh
        container: qc.sec_jumpy-razzmatazz-angelfish
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-carmine-yak.sh
        container: qc.sty_nerdy-lavender-frog
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-sapphire-rhinoceros.sh
        container: qc.sty_woolly-fuchsia-shrimp
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-silver-mouse.sh
        container: qc.uni_shaggy-copper-chipmunk
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-wisteria-iguana.sh
        container: qc.ver_greasy-rose-capuchin
timeout: 5400
