config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: 1.3.6
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-rose-vulture.sh
        container: qc.acc_squirrely-lime-wasp
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-saffron-snake.sh
        container: qc.doc_hilly-green-newt
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-olive-macaw.sh
        container: qc.doc_queasy-white-slug
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-copper-liger.sh
        container: qc.doc_flimsy-charcoal-vole
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-seashell-boar.sh
        container: qc.lic_goopy-lilac-lion
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-scarlet-wrasse.sh
        container: qc.met_cloudy-ruby-dragon
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-scarlet-baboon.sh
        container: qc.sec_lanky-periwinkle-cockroach
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-white-seahorse.sh
        container: qc.sty_ready-flax-skunk
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cinnamon-snail.sh
        container: qc.sty_wheezy-cream-wildebeest
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-brown-heron.sh
        container: qc.ver_snappy-tan-grasshopper
timeout: 5400
