config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: 1.3.5-rc.7
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-russet-eel.sh
        container: qc.acc_stealthy-olivine-ant
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-tan-zorse.sh
        container: qc.doc_shabby-xanthic-crocodile
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-carmine-cockroach.sh
        container: qc.doc_dorky-maroon-avocet
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-sapphire-rat.sh
        container: qc.doc_ugly-sangria-tang
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-corn-ragdoll.sh
        container: qc.lic_lumpy-ecru-cattle
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-platinum-gerbil.sh
        container: qc.met_shaky-chartreuse-barb
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-platinum-snake.sh
        container: qc.sec_bluesy-indigo-dane
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ochre-hamster.sh
        container: qc.sty_snoopy-apricot-russel
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-sangria-macaw.sh
        container: qc.sty_thirsty-saffron-chimpanzee
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-pink-cassowary.sh
        container: qc.ver_droopy-gamboge-raccoon
timeout: 5400
