config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-coral-ant.sh
        container: qc.acc_cloudy-puce-mayfly
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-tan-kiwi.sh
        container: qc.doc_foggy-jade-woodpecker
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cardinal-elephant.sh
        container: qc.doc_foggy-aqua-jaguar
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-saffron-swan.sh
        container: qc.doc_bumpy-bronze-spaniel
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-chestnut-wolverine.sh
        container: qc.lic_chummy-olive-saola
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-tangerine-sponge.sh
        container: qc.met_cheeky-razzmatazz-cat
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-thistle-crab.sh
        container: qc.sec_grumpy-bistre-serval
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-sangria-grouse.sh
        container: qc.sty_scanty-sepia-elephant
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-magenta-chow.sh
        container: qc.sty_gloppy-grey-lionfish
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-sapphire-camel.sh
        container: qc.uni_hazy-zucchini-fowl
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-aquamarine-termite.sh
        container: qc.ver_zippy-smalt-hippopotamus
timeout: 5400
