config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: v1.3.5-rc.1
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-brass-lemur.sh
        container: qc.acc_flimsy-razzmatazz-devil
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-flax-gharial.sh
        container: qc.doc_messy-chocolate-panda
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-zucchini-ant.sh
        container: qc.doc_flaky-auburn-ray
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-sangria-numbat.sh
        container: qc.doc_foggy-cerulean-blue
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-pumpkin-wombat.sh
        container: qc.lic_snoopy-corn-corgi
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cornflower-husky.sh
        container: qc.met_woozy-teal-ferret
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-crimson-tzu.sh
        container: qc.sec_paltry-scarlet-uakari
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-champagne-frog.sh
        container: qc.sty_squirrely-tan-otter
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-viridian-barnacle.sh
        container: qc.sty_slaphappy-periwinkle-panda
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-sapphire-loon.sh
        container: qc.ver_beady-flax-goat
timeout: 5400
