config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: 1.2.4
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-copper-spaniel.sh
        container: qc.acc_lousy-sapphire-chin
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-goldenrod-raccoon.sh
        container: qc.doc_stuffy-fuchsia-ocelot
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-bronze-schnauzer.sh
        container: qc.doc_pasty-amber-cow
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-gamboge-mist.sh
        container: qc.doc_chummy-alizarin-chihuahua
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-burgundy-havanese.sh
        container: qc.lic_slimy-lime-cougar
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-aqua-kiwi.sh
        container: qc.sec_lumpy-turquoise-uakari
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-tomato-bordeaux.sh
        container: qc.sty_wiggy-pear-fish
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-white-deer.sh
        container: qc.ver_wheezy-sepia-stoat
timeout: 5400
