config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-firebrick-gorilla.sh
        container: qc.acc_scaly-goldenrod-skunk
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-carmine-wolverine.sh
        container: qc.doc_sleazy-magnolia-dachsbracke
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ecru-forest.sh
        container: qc.doc_shaky-wisteria-otter
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-amethyst-peccary.sh
        container: qc.doc_gimpy-gold-discus
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-charcoal-woodlouse.sh
        container: qc.lic_paltry-buff-nightingale
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-lilac-crab.sh
        container: qc.met_wimpy-saffron-corgi
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cardinal-retriever.sh
        container: qc.sec_surly-persimmon-oriole
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-rose-echidna.sh
        container: qc.sty_sunny-auburn-grouse
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-auburn-vulture.sh
        container: qc.sty_snoopy-flax-retriever
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-mauve-antelope.sh
        container: qc.ver_sloppy-black-toucan
timeout: 5400
