config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-russet-sparrow.sh
        container: qc.acc_cozy-gold-discus
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-gamboge-malamute.sh
        container: qc.doc_wheezy-salmon-rabbit
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-aquamarine-wrasse.sh
        container: qc.doc_pasty-malachite-lynx
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-burgundy-fly.sh
        container: qc.doc_cheeky-orchid-earwig
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cyan-molly.sh
        container: qc.lic_scanty-tan-oriole
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-denim-cattle.sh
        container: qc.met_hasty-lilac-scorpion
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-tomato-toucan.sh
        container: qc.sec_shaggy-champagne-loon
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-cinnabar-corgi.sh
        container: qc.sty_surly-black-heron
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cornflower-chihuahua.sh
        container: qc.sty_boozy-rust-bracke
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cerise-moorhen.sh
        container: qc.uni_thirsty-green-quetzal
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-goldenrod-guppy.sh
        container: qc.ver_scanty-lime-mole
timeout: 5400
