config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-tan-wallaby.sh
        container: qc.acc_lovely-thistle-caiman
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-jade-lion.sh
        container: qc.doc_squirrely-platinum-baboon
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-amber-owl.sh
        container: qc.doc_leaky-brown-uguisu
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-tangerine-pig.sh
        container: qc.doc_lumpy-buff-snake
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-viridian-gerbil.sh
        container: qc.lic_dorky-olive-rattlesnake
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-corn-gharial.sh
        container: qc.met_messy-aquamarine-monkey
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-tan-tarantula.sh
        container: qc.sec_cozy-ochre-bloodhound
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-khaki-dolphin.sh
        container: qc.sty_bluesy-amaranth-uakari
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-harlequin-booby.sh
        container: qc.sty_craggy-white-pinscher
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-goldenrod-kingfisher.sh
        container: qc.ver_breezy-saffron-avocet
timeout: 5400
