config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-yellow-antelope.sh
        container: qc.acc_wheezy-razzmatazz-cow
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-firebrick-cougar.sh
        container: qc.doc_snippy-persimmon-greyhound
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-emerald-fossa.sh
        container: qc.doc_tacky-denim-hamster
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chestnut-kudu.sh
        container: qc.doc_baggy-aquamarine-dunker
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-amber-hippopotamus.sh
        container: qc.lic_foggy-razzmatazz-llama
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-sapphire-quoll.sh
        container: qc.met_clammy-mustard-octopus
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-viridian-drever.sh
        container: qc.sec_hilly-peach-alligator
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cinnamon-turkey.sh
        container: qc.sty_boozy-rust-ragdoll
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-rose-whale.sh
        container: qc.sty_boozy-periwinkle-flounder
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-maroon-fossa.sh
        container: qc.uni_leaky-lime-salamander
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-amber-frigatebird.sh
        container: qc.ver_sunny-ecru-frog
timeout: 5400
