config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-orange-worm.sh
        container: qc.acc_crabby-buff-vole
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-tomato-forest.sh
        container: qc.doc_cozy-cornflower-rabbit
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chestnut-wallaby.sh
        container: qc.doc_sloppy-cornflower-labradoodle
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-sepia-dachsbracke.sh
        container: qc.doc_sunny-teal-dugong
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-seashell-salamander.sh
        container: qc.lic_gamy-cerise-ostrich
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.beady-charcoal-wrasse.sh
        container: qc.met_freaky-firebrick-chinook
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-crimson-mouse.sh
        container: qc.sec_dorky-sapphire-centipede
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-harlequin-tarantula.sh
        container: qc.sty_snippy-charcoal-snail
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-firebrick-ocelot.sh
        container: qc.sty_sloppy-goldenrod-uguisu
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cerulean-turkey.sh
        container: qc.uni_breezy-burgundy-gopher
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-taupe-bandicoot.sh
        container: qc.ver_whiny-peach-leopard
timeout: 5400
