config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: 1.1.8
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cerulean-axolotl.sh
        container: qc.acc_zippy-saffron-ladybird
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-taupe-moth.sh
        container: qc.doc_flaky-cerulean-ostrich
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-persimmon-bonobo.sh
        container: qc.doc_boozy-crimson-octopus
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-amaranth-maltese.sh
        container: qc.doc_ready-olivine-burmese
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-tomato-insect.sh
        container: qc.lic_beady-charcoal-shark
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-brown-rattlesnake.sh
        container: qc.sec_goopy-orchid-badger
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-chestnut-anteater.sh
        container: qc.sty_pokey-apricot-bat
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-brass-binturong.sh
        container: qc.ver_snazzy-cinnabar-hyrax
timeout: 5400
