config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-blue-sheepdog.sh
        container: qc.acc_scummy-tan-cattle
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-magenta-gharial.sh
        container: qc.doc_scummy-khaki-quail
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-khaki-antelope.sh
        container: qc.doc_silly-smalt-bombay
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-bronze-falcon.sh
        container: qc.doc_nerdy-heliotrope-nightingale
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-olivine-balinese.sh
        container: qc.lic_shaggy-chartreuse-mongoose
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.surly-ultramarine-argentino.sh
        container: qc.met_crabby-smalt-hyrax
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-olive-dachshund.sh
        container: qc.sec_randy-olivine-seahorse
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-ruby-gorilla.sh
        container: qc.sty_wiggy-dandelion-shark
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-mauve-hyrax.sh
        container: qc.sty_muzzy-peach-loon
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-turquoise-cockroach.sh
        container: qc.ver_sunny-cream-lizard
timeout: 5400
