config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-sapphire-bullfrog.sh
        container: qc.acc_squirrely-sangria-sparrow
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-violet-stingray.sh
        container: qc.doc_craggy-lime-cougar
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-lilac-donkey.sh
        container: qc.doc_whiny-cyan-bear
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-maroon-pig.sh
        container: qc.doc_bumpy-olivine-bombay
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-buff-caracal.sh
        container: qc.lic_scummy-platinum-drever
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-brown-millipede.sh
        container: qc.met_sleazy-ecru-fish
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-tangerine-antelope.sh
        container: qc.sec_thirsty-copper-lynx
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-red-turtle.sh
        container: qc.sty_scanty-alizarin-neanderthal
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-copper-mongrel.sh
        container: qc.sty_clammy-yellow-hyena
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-indigo-zorse.sh
        container: qc.uni_flabby-purple-horse
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-ochre-toad.sh
        container: qc.ver_scaly-pear-eleuth
timeout: 5400
