config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-dandelion-whippet.sh
        container: qc.acc_sunny-auburn-raccoon
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-firebrick-orangutan.sh
        container: qc.doc_boozy-sapphire-nightingale
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-peach-camel.sh
        container: qc.doc_fuzzy-black-mongrel
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-wisteria-booby.sh
        container: qc.doc_gummy-tomato-cuscus
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-wheat-vole.sh
        container: qc.lic_chewy-harlequin-warthog
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-lavender-quail.sh
        container: qc.met_snippy-mauve-serval
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-heliotrope-hyena.sh
        container: qc.sec_bumpy-eggplant-hamster
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-tomato-falcon.sh
        container: qc.sty_muggy-cinnabar-tiger
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-ivory-eleuth.sh
        container: qc.sty_whiny-tomato-paradise
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-azure-warthog.sh
        container: qc.uni_pasty-olive-caracal
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-aqua-bee.sh
        container: qc.ver_trippy-salmon-spoonbill
timeout: 5400
