config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-pink-ray.sh
        container: qc.acc_hasty-eggplant-snail
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-razzmatazz-kingfisher.sh
        container: qc.doc_hilly-cobalt-chicken
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-champagne-buffalo.sh
        container: qc.doc_clammy-carmine-binturong
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-firebrick-binturong.sh
        container: qc.doc_hilly-persimmon-flounder
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-magnolia-beaver.sh
        container: qc.lic_foggy-pear-ibis
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-aquamarine-squirt.sh
        container: qc.met_stinky-tomato-antelope
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homey-corn-toucan.sh
        container: qc.sec_slimy-coral-sponge
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-tangerine-sparrow.sh
        container: qc.sty_fuzzy-red-mouse
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-grey-mandrill.sh
        container: qc.sty_droopy-ecru-chamois
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-seashell-deer.sh
        container: qc.uni_silly-olive-guppy
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-pumpkin-quoll.sh
        container: qc.ver_sleazy-lime-magpie
timeout: 5400
