config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-dandelion-fossa.sh
        container: qc.acc_clammy-taupe-capuchin
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-celadon-kakapo.sh
        container: qc.doc_shaggy-cinnabar-buzzard
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-ecru-dachshund.sh
        container: qc.doc_homely-indigo-frog
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-fuchsia-coyote.sh
        container: qc.doc_randy-gold-newfoundland
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-ecru-barb.sh
        container: qc.lic_scummy-scarlet-beetle
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-silver-kiwi.sh
        container: qc.met_tasty-ivory-orangutan
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-xanthic-collie.sh
        container: qc.sec_slimy-black-scorpion
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-malachite-chameleon.sh
        container: qc.sty_skanky-denim-snake
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-chocolate-lobster.sh
        container: qc.sty_ready-corn-burmese
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.randy-chartreuse-dolphin.sh
        container: qc.uni_gloppy-thistle-okapi
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-alizarin-llama.sh
        container: qc.ver_crappy-fuchsia-bison
timeout: 5400
