config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: v1.3.5-rc.3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-celadon-havanese.sh
        container: qc.acc_homely-viridian-uakari
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-razzmatazz-cuttlefish.sh
        container: qc.doc_shabby-aquamarine-snake
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-celadon-catfish.sh
        container: qc.doc_woolly-sapphire-husky
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-magenta-mayfly.sh
        container: qc.doc_muggy-flax-hyena
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-malachite-foxhound.sh
        container: qc.lic_trippy-celadon-angora
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-auburn-cow.sh
        container: qc.met_stuffy-auburn-otter
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-zucchini-frigatebird.sh
        container: qc.sec_hilly-magenta-budgerigar
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-yellow-squid.sh
        container: qc.sty_craggy-cerulean-mongrel
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cornflower-bandicoot.sh
        container: qc.sty_stuffy-amber-jackal
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-xanthic-mammoth.sh
        container: qc.ver_pasty-chartreuse-kakapo
timeout: 5400
