config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-teal-coral.sh
        container: qc.acc_baggy-taupe-eleuth
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-salmon-ladybird.sh
        container: qc.doc_sleazy-pink-chamois
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-lavender-eleuth.sh
        container: qc.doc_stealthy-black-cuttlefish
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-seashell-bat.sh
        container: qc.doc_bumpy-vermilion-foxhound
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-magenta-anteater.sh
        container: qc.lic_hazy-ecru-lizard
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-olivine-pig.sh
        container: qc.met_boozy-persimmon-dalmatian
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-vermilion-deer.sh
        container: qc.sec_silly-apricot-vole
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-periwinkle-ostrich.sh
        container: qc.sty_baggy-zucchini-mammoth
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-pumpkin-bandicoot.sh
        container: qc.sty_droopy-lavender-badger
  QC.Uni:
    repos:
      github.com/indigo-dc/udocker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-alizarin-markhor.sh
        container: qc.uni_snoopy-alizarin-peccary
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-seashell-bordeaux.sh
        container: qc.ver_whiny-viridian-walrus
timeout: 5400
