config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: 1.3.0
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-eggplant-toad.sh
        container: qc.acc_craggy-cinnabar-baboon
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-mauve-alligator.sh
        container: qc.doc_grumpy-malachite-bordeaux
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-eggplant-bloodhound.sh
        container: qc.doc_lumpy-yellow-dolphin
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-vermilion-oriole.sh
        container: qc.doc_baggy-eggplant-emu
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-tomato-foxhound.sh
        container: qc.lic_shaggy-cerise-tetra
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-sangria-hare.sh
        container: qc.met_surly-orchid-macaque
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-puce-worm.sh
        container: qc.sec_gamy-cobalt-rat
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-saffron-rottweiler.sh
        container: qc.sty_silly-beige-jaguar
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-ivory-baboon.sh
        container: qc.sty_muggy-indigo-angelfish
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-xanthic-cheetah.sh
        container: qc.ver_freaky-celadon-cichlid
timeout: 5400
