config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: 1.3.5-rc.5
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-brown-bobcat.sh
        container: qc.acc_crappy-lavender-buffalo
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cornflower-peccary.sh
        container: qc.doc_surly-ultramarine-centipede
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-saffron-crab.sh
        container: qc.doc_cloudy-yellow-oyster
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-firebrick-chow.sh
        container: qc.doc_pretty-saffron-pig
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-amber-coati.sh
        container: qc.lic_scummy-bronze-eleuth
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.homey-ivory-dugong.sh
        container: qc.met_pretty-malachite-foxhound
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-salmon-dragon.sh
        container: qc.sec_crabby-apricot-oyster
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ready-coral-wolf.sh
        container: qc.sty_gloppy-red-bordeaux
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-celadon-snail.sh
        container: qc.sty_trippy-purple-fly
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-apricot-beaver.sh
        container: qc.ver_woolly-indigo-opossum
timeout: 5400
