config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: 1.3.5
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-carmine-gar.sh
        container: qc.acc_sunny-tangerine-olm
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lilac-shrimp.sh
        container: qc.doc_crabby-chartreuse-magpie
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-gold-hyena.sh
        container: qc.doc_woolly-olivine-bison
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-fuchsia-cuttlefish.sh
        container: qc.doc_zippy-scarlet-mammoth
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cyan-uakari.sh
        container: qc.lic_messy-blue-corgi
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-saffron-kangaroo.sh
        container: qc.met_trippy-chestnut-urchin
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-auburn-lobster.sh
        container: qc.sec_trippy-bronze-cuscus
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-purple-wolfhound.sh
        container: qc.sty_lumpy-beige-crab
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-brown-sheepdog.sh
        container: qc.sty_hilly-zucchini-chameleon
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-plum-quail.sh
        container: qc.ver_frumpy-lilac-walrus
timeout: 5400
